name: build-push-docker image to docker hub
on: 
  push: 
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker docker/login-action
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/demo-docker:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/myapp:cache
          cache-to: type=inline,mode=max