name: Docker build and push image to Docker Hub
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.1.5
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with: 
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
      - name: Logout from Docker Hub
        run: | 
          docker logout