version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - ENV=production
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - /Users/psnehi/Documents/mongo-server/:/data/db/
  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin 
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
    ports:
      - "8081:8081"
  # node:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     tags:
  #       - psnehi/docker-test:latest
  #   image: psnehi/docker-test:latest
  #   container_name: node
  #   restart: always
  #   ports:
  #     - "5050:5050"