version: '3.8'
services:
  mongo:
    image: mongo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
      - ENV=production
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - /mongo-server/:/data/db/
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin 
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
    ports:
      - "8081:8081"